In [ ]:
import tensorflow as tf
print(f"Versi: \n{tf.__version__}") # ²³

Versi: 
2.21.0


Cell 2 - Turunan Sederhana
Misalnya:
    y = x²
Turunannya:
    dx|dy = 2x

Jika x=3, maka hasilnya adalah 6.

In [59]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape: # y = 3² = 9
    y = x ** 2

grad = tape.gradient(y, x)
print(f"y: \n{y.numpy()}")
print(f"dy/dx: ", grad.numpy())

y: 
9.0
dy/dx:  6.0


In [60]:
# y = x³ + 2x + 1
x = tf.Variable(2.0)

with tf.GradientTape() as tape:
    y = x ** 3 + 2 * x + 1

grad = tape.gradient(y,x) #dy/dx = 3(2²)+2
                          #= 12+2

print(f"y: \n{y}")
print(f"dy/dx: \n{grad.numpy()}")

y: 
13.0
dy/dx: 
14.0


In [61]:
x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as tape:
    z = x ** 2 + y ** 2

grad = tape.gradient(z, [x,y])
print(f"dz/dx: \n{grad[0].numpy()}")
print(f"dz/dy: \n{grad[1].numpy()}")

dz/dx: 
4.0
dz/dy: 
6.0


In [62]:
x = tf.Variable([1.0, 2.0, 3.0])
with tf.GradientTape() as tape:
    y = x ** 2

grad = tape.gradient(y, x)
print(grad.numpy())

[2. 4. 6.]


In [63]:
x = tf.Variable([1.0, 2.0, 3.0])
with tf.GradientTape() as tape:
    y = tf.reduce_sum(x ** 2)

grad = tape.gradient(y, x)
print(f"grad: \n{grad.numpy()}")

grad: 
[2. 4. 6.]


In [64]:
x = tf.Variable(3.0)
with tf.GradientTape(
    persistent=True
) as tape:
    
    y = x ** 2
    z = x ** 3
dy = tape.gradient(y, x)
dz = tape.gradient(z,x)
print(f"dy/dx: \n{dy.numpy()}")
print(f"dz/dx: \n{dz.numpy()}")

dy/dx: 
6.0
dz/dx: 
27.0


In [65]:
berat = tf.Variable(10.0)
print(f"Awal: \n{berat.numpy()}")

berat.assign(20.0)
print(f"Baru: {berat.numpy()}")

Awal: 
10.0
Baru: 20.0


In [66]:
# x mendekati 5
# Loss = (x - 5)²
x = tf.Variable(0.0)
learning_rate = 0.1
for i in range(20):
    with tf.GradientTape() as tape:
        loss = (x - 5) ** 2
    grad = tape.gradient(loss,x)

    x.assign_sub(
        learning_rate * grad
    )
    print(
        f"Epoch {i+1}",
        "x =", x.numpy(),
        "loss =", loss.numpy()
    )


Epoch 1 x = 1.0 loss = 25.0
Epoch 2 x = 1.8 loss = 16.0
Epoch 3 x = 2.44 loss = 10.240001
Epoch 4 x = 2.9520001 loss = 6.5536
Epoch 5 x = 3.3616002 loss = 4.1943035
Epoch 6 x = 3.68928 loss = 2.684354
Epoch 7 x = 3.9514241 loss = 1.7179868
Epoch 8 x = 4.1611395 loss = 1.0995114
Epoch 9 x = 4.328912 loss = 0.70368695
Epoch 10 x = 4.4631295 loss = 0.4503594
Epoch 11 x = 4.5705037 loss = 0.2882299
Epoch 12 x = 4.656403 loss = 0.18446706
Epoch 13 x = 4.7251225 loss = 0.11805885
Epoch 14 x = 4.780098 loss = 0.075557664
Epoch 15 x = 4.8240786 loss = 0.048356906
Epoch 16 x = 4.859263 loss = 0.030948354
Epoch 17 x = 4.88741 loss = 0.01980692
Epoch 18 x = 4.9099283 loss = 0.012676471
Epoch 19 x = 4.9279428 loss = 0.008112907
Epoch 20 x = 4.942354 loss = 0.0051922468


In [67]:

x = tf.Variable(0.0)
lr = 0.1

@tf.function
def train_step():
    with tf.GradientTape() as tape:
        loss = (x - 5) ** 2

    grad = tape.gradient(loss,x)

    x.assign_sub(
        lr * grad
    )
    return loss

for epoch in range(20):
    loss = train_step()

    print(
        epoch + 1,
        x.numpy(),
        loss.numpy()
    )
    

1 1.0 25.0
2 1.8 16.0
3 2.44 10.240001
4 2.9520001 6.5536
5 3.3616002 4.1943035
6 3.68928 2.684354
7 3.9514241 1.7179868
8 4.1611395 1.0995114
9 4.328912 0.70368695
10 4.4631295 0.4503594
11 4.5705037 0.2882299
12 4.656403 0.18446706
13 4.7251225 0.11805885
14 4.780098 0.075557664
15 4.8240786 0.048356906
16 4.859263 0.030948354
17 4.88741 0.01980692
18 4.9099283 0.012676471
19 4.9279428 0.008112907
20 4.942354 0.0051922468


In [68]:
x = tf.Variable([
    [1.0, 2.0],
    [3.0, 4.0]
])
with tf.GradientTape() as tape:
    y = tf.reduce_sum(x ** 2)
grad = tape.gradient(y, x)
print(grad.numpy())

[[2. 4.]
 [6. 8.]]


In [70]:
# cari nilai minimum dari
# f(x) = x² + 4x + 4
x = tf.Variable(10.0)
lr = 0.1

for epoch in range(50):
    with tf.GradientTape() as tape:
        loss = x ** 2 + 4 * x + 4

    grad = tape.gradient(loss,x )
    x.assign_sub(
        lr * grad
    )
print(f"x: \n{x.numpy()}")
print(f"f(x): \n{loss.numpy()}")


x: 
-1.9998286962509155
f(x): 
0.0
