In [1]:
import tensorflow as tf
print(f"Versi: \n{tf.__version__}")

Versi: 
2.21.0


In [2]:
# Soal Pertama
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0]
])
y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0]
])
print(f"x_train: \n{x_train}")
print(f"y_train: \n{y_train}")

x_train: 
[[1.]
 [2.]
 [3.]]
y_train: 
[[3.]
 [5.]
 [7.]]


In [3]:
# Soal Kedua
w = tf.Variable(
    tf.random.normal((1,1))
)
b = tf.Variable(
    tf.random.normal((1,))
)
print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")

w: 
[[0.27500117]]
b: 
[-2.536887]


In [4]:
# Soal Ketiga
x = tf.constant([[5.0]])
w = tf.constant([[2.0]])
b = tf.constant([[1.0]])

prediksi = tf.matmul(
    x,
    w
) + b
print(f"prediksi: \n{prediksi}")

prediksi: 
[[11.]]


In [5]:
# Soal Keempat
y_true = tf.constant([
    [3.0],
    [5.0]
])
y_pred = tf.constant([
    [2.0],
    [4.0]
])
loss = tf.reduce_mean(
    (y_true - y_pred) ** 2
)
print(f"loss: \n{loss}")

loss: 
1.0


In [6]:
# Soal Kelima
x = tf.constant([[2.0]])
y_true = tf.constant([[5.0]])

w = tf.Variable([[1.0]])
b = tf.Variable([0.0])

with tf.GradientTape() as tape:
    prediksi = tf.matmul(
        x,
        w
    ) + b
    loss = tf.reduce_mean(
        (y_true - y_pred) ** 2
    )
grad_w = tape.gradient(
    loss,
    w
)
print(f"Gradient W: \n{grad_w}")

Gradient W: 
None


In [9]:
# Soal Keenam
x = tf.constant([[2.0]])
y_true = tf.constant([[5.0]])

w = tf.Variable([[1.0]])
b = tf.Variable([0.0])

with tf.GradientTape() as tape:
    prediksi = tf.matmul(
        x,
        w
    ) + b
    loss = tf.reduce_mean(
        (y_true - y_pred) ** 2
    )
grad_w, grad_b = tape.gradient(
    loss,
    [w,b]
)
print(f"grad_w: \n{grad_w}")
print(f"grad_b: \n{grad_b}")
    

grad_w: 
None
grad_b: 
None


In [14]:
# Soal ketujuh
w = tf.Variable([[2.0]])
grad_w = tf.Variable([[0.5]])

lr = 0.1
print(f"Sebelum Update: \n{w.numpy()}")

w.assign_sub(
    lr * grad_w
)
print(f"Sesudah Update: \n{w.numpy()}")

Sebelum Update: 
[[2.]]
Sesudah Update: 
[[1.95]]


In [ ]:
# Soal kedelapan
x_train = tf.constant([
    [1.0],
    [2.0]
])
y_train = tf.constant([
    [3.0],
    [5.0]
])

w = tf.Variable([[1.0]])
b = tf.Variable([0.0])

lr = 0.1

with tf.GradientTape() as tape:
    prediksi = tf.matmul(
        x_train,
        w,
    ) + b
    loss = tf.reduce_mean(
        (y_train - prediksi) ** 2
    )
    grad_w,grad_b = tape.gradient(
        loss,
        [w,b]
    )
    w.assign_sub(
        lr * grad_w
    )
    b.assign_sub(
        lr * grad_b
    )
print(f"loss: \n{loss.numpy()}")
print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")

loss: 
6.5
w: 
[[1.8]]
b: 
[0.5]


In [20]:
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])
y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0]
])
w = tf.Variable([[0.0]])
b = tf.Variable([0.0])

lr = 0.05
for epoch in range(50):
    with tf.GradientTape() as tape:
        prediksi = tf.matmul(
            x_train,
            w
        ) + b
        loss = tf.reduce_mean(
            (y_train - prediksi) ** 2
        )
    grad_w, grad_b = tape.gradient(
        loss,
        [w,b]
    )
    w.assign_sub(
        lr * grad_w
    )
    b.assign_sub(
        lr * grad_b
    )
print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")
print(f"loss: \n{loss.numpy()}")

w: 
[[2.045856]]
b: 
[0.86517775]
loss: 
0.003128757933154702


In [22]:
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])
y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0]
])
w = tf.Variable([[0.0]])
b = tf.Variable([0.0])
lr = 0.05
for epoch in range(100):
    with tf.GradientTape() as tape:
        prediksi = tf.matmul(
            x_train,
            w
        ) + b
        loss = tf.reduce_mean(
            (y_train - prediksi) **2
        )
        grad_w, grad_b = tape.gradient(
            loss,
            [w,b]
        )
        w.assign_sub(
            lr * grad_w
        )
        b.assign_sub(
            lr * grad_b
        )
x_baru = tf.constant([[10.0]])
prediksi_baru = tf.matmul(
    x_baru,
    w,
) +  b

print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")
print(f"prediksi: \n{prediksi}")
print(f"prediksi_baru: \n{prediksi_baru}")


w: 
[[2.0215714]]
b: 
[0.9365772]
prediksi: 
[[2.9575126]
 [4.979412 ]
 [7.0013113]
 [9.023211 ]]
prediksi_baru: 
[[21.15229]]
