In [31]:
import tensorflow as tf

print(f"Versi: \n{tf.__version__}")

Versi: 
2.21.0


w = weight
b = bias
pola ML: 
prediksi = model(x)
loss = fungsi_loss(
    y_true,
    prediksi
)
y = 2x + 1 -> weigh itu 2
              bias itu 1

In [ ]:
# y=2x+1
x_train = tf.constant(
    [[1.0],
    [2.0],
    [3.0],
    [4.0]]
)
y_train = tf.constant(
    [[3.0],
    [5.0],
    [7.0],
    [9.0]]
)
print(f"x_train: \n{x_train}")
print(f"y_train: \n{y_train}")


x_train: 
[[1.]
 [2.]
 [3.]
 [4.]]
y_train: 
[[3.]
 [5.]
 [7.]
 [9.]]


In [33]:
w = tf.Variable(
    tf.random.normal((1, 1))
)

b = tf.Variable(
    tf.random.normal((1,))
)

print(f"weight: \n{w.numpy()}")
print(f"Bias: \n{b.numpy()}")


weight: 
[[0.9258933]]
Bias: 
[1.337648]


In [ ]:
# y=xw+b
prediksi = tf.matmul(
    x_train, # -> ini adalah matrix
    w
) + b

print(f"Prediksi: \n{prediksi.numpy()}")

Prediksi: 
[[2.2635412]
 [3.1894345]
 [4.115328 ]
 [5.041221 ]]


In [ ]:
# Loss = 1/n ∑(y_true- y_pred)² -> ini MSE, semakin kecil semakin bagus untuk AI
prediksi = tf.matmul(
    x_train,
    w
) + b
loss = tf.reduce_mean(
    (y_train - prediksi) ** 2
)
print(f"loss: \n{loss.numpy()}")

loss: 
6.9534454345703125


In [36]:
with tf.GradientTape() as tape:
    prediksi = (
        tf.matmul(
            x_train,
            w    
        ) + b
    )
    loss = tf.reduce_mean(
        (y_train - prediksi) ** 2
    )
grad_w, grad_b = tape.gradient(
    loss,
    [w,b]
)
print(f"Gradient W: \n{grad_w.numpy()}")
print(f"Gradient B: \n{grad_b.numpy()}")

Gradient W: 
[[-14.423361]]
Gradient B: 
[-4.6952376]


In [37]:
learning_rate = 0.01
w.assign_sub(
    learning_rate * grad_w
)
b.assign_sub(
    learning_rate * grad_b
)
print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")

w: 
[[1.0701269]]
b: 
[1.3846004]


In [38]:
learning_rate = 0.01
with tf.GradientTape() as tape:
    prediksi = (
        tf.matmul(
            x_train,
            w
        ) + b
    )
    loss = tf.reduce_mean(
        (y_train - prediksi) ** 2
    )
grad_w, grad_b = tape.gradient(
    loss,
    [w,b]
)
w.assign_sub(
    learning_rate * grad_w
)
b.assign_sub(
    learning_rate * grad_b
)
print(f"loss: \n{loss.numpy()}")

loss: 
4.844749450683594


In [ ]:
w = tf.Variable(
    tf.random.normal((1,1))
)
b = tf.Variable(
    tf.random.normal((1,))
)

learning_rate = 0.01

for epoch in range(500):
    with tf.GradientTape() as tape:
        prediksi = (
            tf.matmul(
                x_train,
                w
            ) + b
        )
        loss = tf.reduce_mean(
            (y_train - prediksi) ** 2
        )
    grad_w, grad_b = tape.gradient(
        loss,
        [w,b]
    )
    w.assign_sub(
        learning_rate * grad_w
    )
    b.assign_sub(
        learning_rate * grad_b
    )
    if epoch % 50 == 0:
        print(
            f"Epoch {epoch}",
            f"Loss {loss.numpy():.4f}"
        )

Epoch 0 Loss 11.5638
Epoch 50 Loss 0.1303
Epoch 100 Loss 0.0965
Epoch 150 Loss 0.0715
Epoch 200 Loss 0.0530
Epoch 250 Loss 0.0393
Epoch 300 Loss 0.0291
Epoch 350 Loss 0.0216
Epoch 400 Loss 0.0160
Epoch 450 Loss 0.0118


In [40]:
print(f"weight: \n{w.numpy()}")
print(f"Bias: \n{b.numpy()}")

weight: 
[[2.077936]]
Bias: 
[0.7708583]


In [ ]:
# y = 2(10) + 1
x_baru = tf.constant([[10.0]])
prediksi = (
    tf.matmul(
        x_baru,
        w
    ) + b
)
print(f"prediksi: \n{prediksi.numpy()}")

prediksi: 
[[21.550219]]


In [42]:
@tf.function
def predict(x):
    return(
        tf.matmul(
            x,
            w
        ) + b
    )
hasil = predict(
    tf.constant([[20.0]])
)
print(f"Hasil: \n{hasil.numpy()}")

Hasil: 
[[42.32958]]


In [43]:
x_train = tf.constant([
    [1.0, 2.0],
    [2.0, 3.0],
    [3.0, 4.0],
    [4.0, 5.0]
])
y_train = tf.constant([
    [8.0],
    [13.0],
    [18.0],
    [23.0]
])
print(f"x_train: \n{x_train}")
print(f"y_train: \n{y_train}")


x_train: 
[[1. 2.]
 [2. 3.]
 [3. 4.]
 [4. 5.]]
y_train: 
[[ 8.]
 [13.]
 [18.]
 [23.]]


In [44]:
w = tf.Variable(
    tf.random.normal(
        (2,1)
    )
)
b = tf.Variable(
    tf.zeros((1,))
)
print(f"w: \n{w.numpy()}")
print(f"b: \n{b.numpy()}")

w: 
[[ 0.16066805]
 [-0.12404377]]
b: 
[0.]


In [45]:
learning_rate = 0.01
for epoch in range(500):
    with tf.GradientTape() as tape:
        prediksi = (
            tf.matmul(
                x_train,
                w
            ) + b
        )
        loss = tf.reduce_mean(
             (y_train - prediksi) ** 2
        )
    grad_w, grad_b = tape.gradient(
        loss,
        [w,b]
    )
    w.assign_sub(
        learning_rate * grad_w
    )
    b.assign_sub(
        learning_rate * grad_b
    )
print(f"Loss: \n{loss}")


Loss: 
0.0007215954246930778
