In [111]:
import tensorflow as tf

In [112]:
# Soal Pertama
class TripleLayer(
    tf.keras.layers.Layer):
    def call(self,inputs):
        return inputs * 3
layer = TripleLayer()
x1 = tf.constant([
    [1.0],
    [2.0],
    [3.0]
])
hasil1 = layer(x1)
print(f"Inputs: \n{x1.numpy()}")
print(f"hasil1: \n{hasil1.numpy()}")

Inputs: 
[[1.]
 [2.]
 [3.]]
hasil1: 
[[3.]
 [6.]
 [9.]]


In [113]:
# Soal Kedua
import tensorflow as tf
class MyDense(
    tf.keras.layers.Layer
):
    def build(self,input_shape):
        self.w = self.add_weight(
            shape=(input_shape[-1],1),
            initializer="random_normal"
        )
        self.b = self.add_weight(
            shape=(1,),
            initializer="zeros"
        )
    def call(self,inputs):
        return(
            tf.matmul(inputs,self.w) + self.b
        )

layer2 = MyDense()
x2 = tf.constant([
    [1.0],
    [2.0],
    
])
hasil2 = layer2(x2)
print(f"layer2; \n{hasil2.numpy()}")


layer2; 
[[0.0623109 ]
 [0.12462181]]


In [114]:
# Soal Ketiga
class MyModel(
    tf.keras.Model
):
    def __init__(self):
        super().__init__()

        self.dense1 = tf.keras.layers.Dense(4, activation="relu")
        self.dense2 = tf.keras.layers.Dense(1)
    def call(self,inputs):
        x3 = self.dense1(inputs)
        return self.dense2(x3)

model3 = MyModel()

x3 = tf.constant([
    [1.0],
    [2.0],
    [3.0]
])
hasil3 = model3(x3)

print(f"Hasil: \n{hasil3.numpy()}")

Hasil: 
[[-0.6796752]
 [-1.3593504]
 [-2.0390258]]


In [115]:
# Soal Keempat
def my_mse(y_true, y_pred):
    return tf.reduce_mean(
        (y_true - y_pred) ** 2
    )
y_true = tf.constant([
    [10.0],
    [20.0]
])
y_pred = tf.constant([
    [12.0],
    [18.0]
])
hasil = my_mse(y_true, y_pred)
print(f"Hasil: \n{hasil.numpy()}")

Hasil: 
4.0


In [ ]:
# Soal Kelima
def my_mse(y_true, y_pred): # ini harusnya def mae
    return tf.reduce_mean(
        tf.abs(y_true - y_pred)
    )
y_true = tf.constant([
    [10.0],
    [20.0]
])
y_pred = tf.constant([
    [12.0],
    [18.0]
])
loss = my_mse(y_true, y_pred)
print(f"hasil MAE: \n{loss.numpy()}")


hasil MAE: 
2.0


In [117]:
# Soal Keenam
X_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])
y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0]
])

dataset = tf.data.Dataset.from_tensor_slices(
    (X_train, y_train)
)
dataset = dataset.batch(2)
print(f"Dataset Siap")

Dataset Siap


In [118]:
# Soal Ketujuh
model = MyModel()
optimizer = tf.keras.optimizers.Adam(
    learning_rate=0.01
)
for epoch in range(20):
    total_loss = 0

    for x_train, y_train in dataset:
        with tf.GradientTape() as tape:
            prediksi = model(x_train)
            
            loss = tf.reduce_mean(
                (y_train - prediksi) ** 2
            )
        
        gradients = tape.gradient(
            loss,model.trainable_variables
        )

        optimizer.apply_gradients(
            zip(gradients, model.trainable_variables)
        )

        total_loss += loss
    if epoch % 10 ==0:
        print(
            f"Epoch {epoch}",
            f"Loss  {loss}"
        )


Epoch 0 Loss  56.535499572753906
Epoch 10 Loss  38.033843994140625


In [119]:
# Soal Kedelapan
for variable in model.trainable_variables:
    print(variable.name)
    print(variable.numpy())

kernel
[[-1.0783442   0.98653954 -0.13144886 -0.03094307]]
bias
[ 0.          0.39130193  0.         -0.22312972]
kernel
[[ 0.6121632 ]
 [ 0.7167171 ]
 [ 0.241243  ]
 [-0.42689243]]
bias
[0.36485928]


In [120]:
# Soal Kesembilan
prediksi = model(
    tf.constant([
        [10.0],
        [20.0]
    ])
)
print(f"Prediksi:\n{prediksi.numpy()}")

Prediksi:
[[ 7.71601 ]
 [14.786708]]


In [121]:
# Soal kesepuluh
model.save_weights(
    "my_weight.weights.h5"
)
model_baru = MyModel()

dummy = tf.constant([
    [1.0]
])
model_baru(dummy)
model_baru.load_weights(
    "my_weight.weights.h5"
)
hasil = model_baru(
    tf.constant([
        [10.0]
    ])
)
print(f"Hasil: \n{hasil.numpy()}")

Hasil: 
[[7.71601]]
