In [31]:
import tensorflow as tf
print(f"versi: \n{tf.__version__}")

versi: 
2.21.0


In [32]:
a = tf.constant([5, 10, 15])
b = tf.constant([2, 4, 6])

print(f"tambah: \n{a + b}")
print(f"kurang: \n{a - b}")
print(f"kali: \n{a * b}")
print(f"bagi: \n{a / b}")

tambah: 
[ 7 14 21]
kurang: 
[3 6 9]
kali: 
[10 40 90]
bagi: 
[2.5 2.5 2.5]


In [33]:
x = tf.constant([1.0, 4.0, 9.0])

print(f"Akar: \n{tf.sqrt(x)}")
print(f"Kuadrat: \n{tf.square(x)}")
print(f"Pangkat 3: \n{tf.pow(x, 3)}")

Akar: 
[1. 2. 3.]
Kuadrat: 
[ 1. 16. 81.]
Pangkat 3: 
[  1.  64. 729.]


In [34]:
nilai = tf.constant([15, 25, 35, 45, 55])

print(f"Nilai Minimum : \n{tf.reduce_min(nilai)}")
print(f"Nilai Maksimim: \n{tf.reduce_max(nilai)}")
print(f"Jumlah: \n{tf.reduce_sum(nilai)}")
print(f"Rata Rata: \n{tf.reduce_mean(tf.cast(nilai,tf.float32))}")

Nilai Minimum : 
15
Nilai Maksimim: 
55
Jumlah: 
175
Rata Rata: 
35.0


In [35]:
a = tf.constant([
    [2, 4],
    [6, 8]
])

b = tf.constant([
    [1, 3],
    [5, 7]
])

print(f"Penjumlahan: \n{a + b}")
hasil = tf.matmul(a,b)
print(f"Matmul: \n{hasil}")

Penjumlahan: 
[[ 3  7]
 [11 15]]
Matmul: 
[[22 34]
 [46 74]]


In [ ]:
# Soal Kelima
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
vector = tf.constant([10, 20, 30])
trans = tf.transpose(matrix)
print(f"Transpose: \n{trans}")
hasil = matrix + vector
print(f"BoardCasting: \n{hasil}")

data = tf.constant([5, 10, 15, 20, 25])
print(f"Minimum: \n{tf.reduce_min(data)}")
print(f"Maksimum: \n{tf.reduce_max(data)}")
print(f"Jumlah: \n{tf.reduce_sum(data)}")
print(f"rata-rata: \n{tf.reduce_mean(tf.cast(data, tf.float32))}")

for i in data.numpy():
    print(i)

Transpose: 
[[1 4]
 [2 5]
 [3 6]]
BoardCasting: 
[[11 22 33]
 [14 25 36]]
Minimum: 
5
Maksimum: 
25
Jumlah: 
75
Minimum: 
15.0
5
10
15
20
25
