In [186]:
import tensorflow as tf

print(f"Tensorflow Version: {tf.__version__}")

Tensorflow Version: 2.21.0


In [187]:
# Penjumlahan, Pengurangan, Perkalian, dan pembagian
a = tf.constant([10, 20, 30])
b = tf.constant([1, 2, 3])

print(f"a: {a}")
print(f"b: {b}")

print(f"Tambah: {a + b}")
print(f"kurang: {a - b}")
print(f"kali: {a * b}")
print(f"bagi: {a / b}")


a: [10 20 30]
b: [1 2 3]
Tambah: [11 22 33]
kurang: [ 9 18 27]
kali: [10 40 90]
bagi: [10. 10. 10.]


In [188]:
# Fungsi Matematika TensorFlow
x = tf.constant([4.0, 9.0, 16.0])
print(f"Akar: {tf.sqrt(x)}") # -> Akar 
print(f"Kuadrat: {tf.square(x)}") # -> Kuadrat 2
print(f"Pangkat 3: {tf.pow(x,3)}") # -> Kuadrat 3

Akar: [2. 3. 4.]
Kuadrat: [ 16.  81. 256.]
Pangkat 3: [  64.  729. 4096.]


In [189]:
# Nilai Minuimum dan maksimum
data = tf.constant([10, 50, 20, 90, 15])
print(f"Minimum: {tf.reduce_min(data)}") # -> angka min
print(f"Maksimum: {tf.reduce_max(data)}") # -> angka max

Minimum: 10
Maksimum: 90


In [ ]:
# Sum dan Mean
nilai = tf.constant([10, 20, 30, 40, 50])
print(f"Jumlah: {tf.reduce_sum(nilai)}") # Menjumlahkan seluruhnya
print(f"Rata-Rata: {tf.reduce_mean(tf.cast(nilai,tf.float32))}") # cast mengubah int menjadi float 
                                                                 # reduce_mean = menjumlahkan lalu memnagi dengan elementnya
print(f"Ubah data: {tf.cast(nilai,tf.float32)}", ) 

Jumlah: 150
Rata-Rata: 30.0
Ubah data: 
<dtype: 'float32'>


In [191]:
# Matrix Addition
a = tf.constant([
    [1, 2],
    [3, 4]
])

b = tf.constant([
    [5, 6],
    [7, 8]
])

hasil = a + b
print(f"Hasil: \n{hasil}")

Hasil: 
[[ 6  8]
 [10 12]]


In [ ]:
# Matrix Multiplication
a = tf.constant([
    [1, 2],
    [3, 4]
])
b = tf.constant([
    [5, 6],
    [7, 8]
])
hasil = tf.matmul(a,b) # Gak usah diapalin
print(f"hasil: \n{hasil}")

hasil: 
[[19 22]
 [43 50]]


In [ ]:
# Transpose Matrix
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"matrix: \n{matrix}")

transpose  = tf.transpose(matrix) # dari baris ke kolom in
print(f"Transpose: \n{transpose}")

matrix: 
[[1 2 3]
 [4 5 6]]
Transpose: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Boardcasting dengan scalar
tensor = tf.constant([1, 2, 3, 4])  
hasil = tensor + 10 # Menambah element
print(f"Hasil: \n{hasil}")

Hasil: 
[11 12 13 14]


In [195]:
# Boardcasting dengan Vector
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
vector = tf.constant([10, 20, 30])
hasil = matrix + vector
print(f"Hasil: \n{hasil}")

Hasil: 
[[11 22 33]
 [14 25 36]]


In [196]:
# For Loop pada Tensor
tensor = tf.constant([10, 20, 30, 40, 50])
for i in tensor:
    print(i.numpy())

10
20
30
40
50


In [197]:
# If else
nilai = tf.constant(85)
if nilai.numpy() >= 75:
    print(f"Lulus")
else:
    print(f"Tidak Lulus")



Lulus


In [198]:
# While Loop
i = tf.Variable(1)
while i.numpy() <= 5:
    print(i.numpy())
    i.assign_add(1)

1
2
3
4
5


In [199]:
# Studi Kasus Mini
nilai_mahasiswa =  tf.constant([80, 70, 90, 85, 95])
print(f"Jumlah:  \n{tf.reduce_sum(nilai_mahasiswa)}")
print("Rata-Rata:\n",tf.reduce_mean(
    tf.cast(nilai_mahasiswa, tf.float32)
))

print(f"Nilai Tertinggi: \n{tf.reduce_max(nilai_mahasiswa)}")
print(f"Nilai Terendah: \n{tf.reduce_min(nilai_mahasiswa)}")

Jumlah:  
420
Rata-Rata:
 tf.Tensor(84.0, shape=(), dtype=float32)
Nilai Tertinggi: 
95
Nilai Terendah: 
70
