In [ ]:
# Soal Pertama
import tensorflow as tf

tensor = tf.constant([
    [1,2],
    [3,4],
    [5,6]
])
print(f"Tensor: \n{tensor}\n")
print(f"Shape tensor: \n{tensor.shape}\n")
reshape1 = tf.reshape(tensor,(2,3))
print(f"reshape1: \n{reshape1}\n")
print(f"Shape reshape1: \n{reshape1.shape}\n")

In [ ]:
# Soal Kedua
import tensorflow as tf
tensor = tf.constant([
    [10, 20, 30],
    [40, 50, 60]
])
print(f"baris pertama: \n{tensor[0]}\n")
print(f"baris Kedua: \n{tensor[1]}\n")
print(f"element: \n{tensor[1][2]}\n")

In [ ]:
# Soal Ketiga
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"Kolom Pertama: \n{tensor[:,0]}\n")
print(f"Kolom ketiga: \n{tensor[:,2]}\n")
print(f"dua kolom pertama: \n{tensor[:,:2]}")

In [ ]:
# Soal Keempat
import tensorflow as tf
a = tf.constant([
    [1, 2],
    [3, 4]
])
b = tf.constant([
    [5, 6],
    [7, 8]
])
gabung_baris = tf.concat([a,b], axis=0)
print(f"concat axis 0 \n{gabung_baris}\n")

gabung_kolom = tf.concat([a,b], axis=1)
print(f"concat axis 1 \n{gabung_kolom}\n")

stack = tf.stack([a,b])
print(f"stack: \n{stack}\n")
print(f"Shape Stack: \n{stack.shape}\n")

concat axis 0 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concat axis 1 
[[1 2 5 6]
 [3 4 7 8]]

stack: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape Stack: 
(2, 2, 2)



In [3]:
# Soal Kelima
import tensorflow as tf
data = tf.constant([
    [10, 20, 30],
    [40, 50, 60]
])
print(f"Shape data: \n{data.shape}\n")
ukuran = tf.size(data)
print(f"Size: \n{ukuran}\n")
print(f"Kolom kedua: \n{data[:, 1]}\n")
data_reshape = tf.reshape(data, [3,2])
print(f"data reshape: \n{data_reshape}\n")

expand_dims = tf.expand_dims(data, axis=0)
print(f"Expand: \n{expand_dims}\n")


print(f"shape: \n{expand_dims.shape}\n")

tensor = tf.constant([
    [[1],
     [2],
     [3]]
])
squ = tf.squeeze(tensor)
print(f"Squeeze: \n{squ}\n")
print(f"Shape tensor: \n{squ.shape}\n")

Shape data: 
(2, 3)

Size: 
6

Kolom kedua: 
[20 50]

data reshape: 
[[10 20]
 [30 40]
 [50 60]]

Expand: 
[[[10 20 30]
  [40 50 60]]]

shape: 
(1, 2, 3)

Squeeze: 
[1 2 3]

Shape tensor: 
(3,)

