In [ ]:
import tensorflow as tf
from tensorflow import __version__
print("TensorFlow Version: ", __version__ )

Reshape = Mengubah bentuk tensor tanpa mengubah isi data
indexing = mengambil satu element
slicing = Mengambil sebagian tensor
concat = menggabungkan tensor
stack = menambah dimensi baru lalu menggabungkan tensor
Expand Dims = Menambah dimensi atau []
Squeeze = Menghapus dimensi yang ukurannya 1 atau []
: = ambil semuanya
[:, 0] = ambil semuanya, kolom pertama
[:, :2] = semua baris, kolom 0 sampai sebelum 2


In [ ]:
# MEMBUAT TENSOR
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
print("\nTensor Awal")
print(tensor)

In [ ]:
# RESHAPE
reshape_1 = tf.reshape(tensor, (3,2))
print(f"Reshape (3,2): \n{reshape_1}")

reshape_2 = tf.reshape(tensor, (6,))
print(f"Reshape (6, ): \n{reshape_2}")

In [ ]:
# INDEXING
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Baris Pertama: \n{tensor[0]}") 
print(f"Baris kedua: \n{tensor[1]}")
print(f"Elemen [0][1]: \n{tensor[0][1].numpy()}") # Baris ke-1, element ke -2

In [ ]:
# SLICING
import tensorflow as tf
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"Kolom Permata: \n{tensor[:, 0]}") 
print(f"Kolom Kedua: \n{tensor[:, 1]}")
print(f"2 Kolom Pertama: \n{tensor[:, :2]}")

In [6]:
import tensorflow as tf
# CONCATENATE
a = tf.constant([
    [1, 2],
    [3, 4]
])

b = tf.constant([
    [5, 6],
    [7, 8]
])

gabung_baris = tf.concat([a,b],axis=0)
print(f"Gabung baris: \n{gabung_baris}")

gabung_kolom = tf.concat([a,b],axis=1)
print(f"gabung kolom: \n{gabung_kolom}")

Gabung baris: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
gabung kolom: 
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# STACK
stack = tf.stack([a,b])
print(f"Stack: \n{stack}")

print(f"Shape Stack: \n{stack.shape}")

In [14]:
# EXPAND DIMS
vector = tf.constant([10, 20, 30, 40])
print(f"Vector: \n{vector}\n")

expand = tf.expand_dims(vector, axis=0)
print(f"Expand Axis 0: \n{expand}\n")

print(f"Shape: \n{expand.shape}\n")

expand2 = tf.expand_dims(vector, axis=1)
print(f"Expand Axis 1: \n{expand2}\n")

print(f"Shape: \n{expand2.shape}")

Vector: 
[10 20 30 40]

Expand Axis 0: 
[[10 20 30 40]]

Shape: 
(1, 4)

Expand Axis 1: 
[[10]
 [20]
 [30]
 [40]]

Shape: 
(4, 1)


In [ ]:
# SQUEEZE
tensor_baru = tf.constant([
    [[1],
    [2],
    [3]]
])
print(f"Tensor Sebelum Squeeze: \n{tensor_baru}\n")
print(f"Shape: \n{tensor_baru.shape}\n")

squezze = tf.squeeze(tensor_baru)
print(f"Tensor setelah squezze: \n{squezze}\n")
print(f"Shape: \n{squezze.shape}")

In [11]:
# FOR LOOP
for baris in tensor:
    print(baris.numpy())

[1 2 3]
[4 5 6]


In [12]:
# While Loop
i = tf.Variable(0)
while i.numpy() < tensor.shape[0]:
    print(f"{tensor[i.numpy()].numpy()}")
    i.assign_add(1)



[1 2 3]
[4 5 6]


In [13]:
# IF ELSE
jumlah_elemen = tf.size(tensor)
if jumlah_elemen.numpy() > 5:
    print(f"\nTensor Besar")
else:
    print(f"Tensor Kecil")


Tensor Besar


In [ ]:
# Latihan
data = tf.constant([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(f"Data: \n{data}\n")
print(f"Shape: \n{data.shape}\n")
print(f"Baris Pertama: \n{data[0]}\n")
print(f"baris Kedua: \n{data[:,1]}")

ubah = tf.reshape(data, (1,9))
print(f"Reshape: \n{ubah}")