In [2]:
import tensorflow as tf
print(f"Versi: {tf.__version__}")

Versi: 2.21.0


Sequential = input -> layer 1 -> Layer 2 -> Output
optimizer="sgd" = Stohastic Gradient Descent -> sama seperti assign_sub()
activation="relu" 
activation = Fungsi yang mengubah output neuron
ReLU = f(x)=max(0,x)
Sigmoid = mengubah angka menjadi = 0 sampai 1
Dense = y = w1x1 + w2x2 + b
(shape) = (jumlah_data, jumlah_fitur)

In [3]:
# y = 2x + 1
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])
y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0]
])
print(f"x_train: \n{x_train}")
print(f"y_train: \n{y_train}")

x_train: 
[[1.]
 [2.]
 [3.]
 [4.]]
y_train: 
[[3.]
 [5.]
 [7.]
 [9.]]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1) # Otomatis memiliki weight(w) dan Bias(b)
])
model.build(input_shape=(None, 1)) # 1 nya tergantung kolom di x_train
print(f"Model Summary: \n{model.summary()}")

print(f"Weight Awal: \n{model.weights[0].numpy()}")

print(f"Bias Awal: \n{model.weights[1].numpy()}")

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

Model Summary: 
None
Weight Awal: 
[[0.50744545]]
Bias Awal: 
[0.]


In [5]:
model.compile(
    optimizer="sgd",
    loss="mse"
)
history = model.fit(
    x_train,
    y_train,
    epochs=100,
    verbose=0
)
print(f"Training selesai\n")


print(f"Weight Akhir: \n{model.weights[0].numpy()}")

print(f"Bias Akhir: \n{model.weights[1].numpy()}")

print(f"Loss Terakhir: \n{history.history['loss'][-1]}")
print(f"model: \n{model}")

Training selesai

Weight Akhir: 
[[2.111211]]
Bias Akhir: 
[0.67302555]
Loss Terakhir: 
0.017963051795959473
model: 
<Sequential name=sequential, built=True>


In [6]:
prediksi = model.predict(
    tf.constant([
        [5.0],
        [10.0],
        [20.0]
    ]),
    verbose=0
)
print(f"Prediksi")

for i, hasil in enumerate(prediksi):
    print(f"Data ke-{i+1}: {hasil[0]}")

Prediksi
Data ke-1: 11.229080200195312
Data ke-2: 21.78513526916504
Data ke-3: 42.897247314453125


In [7]:
model_relu = tf.keras.Sequential([
    tf.keras.layers.Dense(
        4, # 4 neuron + ReLU
        activation="relu"
    ),
    tf.keras.layers.Dense(
        1
    )
])
model_relu.build(
    input_shape=(None, 1)
)
model_relu.summary()
x = tf.constant([
    [-5.0],
    [0.0],
    [5.0]
])
relu = tf.keras.layers.ReLU()
print(f"input: \n{x.numpy()}")
print(f"Output: \n{relu(x).numpy()}")

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 4)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

input: 
[[-5.]
 [ 0.]
 [ 5.]]
Output: 
[[0.]
 [0.]
 [5.]]


In [8]:
x = tf.constant([
    [-5.0],
    [0.0],
    [5.0]
])

hasil = tf.nn.sigmoid(x)
print(f"Input: \n{x.numpy()}")
print(f"Output Sigmoid: \n{hasil.numpy()}")


Input: 
[[-5.]
 [ 0.]
 [ 5.]]
Output Sigmoid: 
[[0.00669285]
 [0.5       ]
 [0.9933072 ]]


In [9]:
x_train = tf.constant([
    [1.0, 2.0],
    [2.0, 3.0],
    [3.0, 4.0],
    [4.0, 5.0]
])
y_train = tf.constant([
    [8.0],
    [13.0],
    [18.0],
    [23.0]
])
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

model.compile(
    optimizer="sgd",
    loss="mse"
)
model.fit(
    x_train,
    y_train,
    epochs=300,
    verbose=0
)
print(f"Training Selesai")
print(f"Weight:\n {model.weights[0].numpy()}")
print(f"Bias: \n{model.weights[1].numpy()}")

prediksi = model.predict(
    tf.constant([[10.0, 11.0]]),
    verbose = 0
)
print(f"Prediksi [10,11]: \n{prediksi}")

Training Selesai
Weight:
 [[2.0995543]
 [2.7993665]]
Bias: 
[0.49255338]
Prediksi [10,11]: 
[[52.281128]]


In [10]:
model.save("model_pertama.keras")
print(f"Model Berhasil disimpan")

model_baru = tf.keras.models.load_model(
    "model_pertama.keras"
)
print(f"Model Berhasil Di-Load")

model_baru.summary()
hasil = model_baru.predict(
    tf.constant([[10.0, 11.0]]),
    verbose=0
)
print(f"Prediksi Setelah Load: \n{hasil}")


Model Berhasil disimpan
Model Berhasil Di-Load


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5 (24.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

Prediksi Setelah Load: 
[[52.281128]]
