In [ ]:
import tensorflow as tf
print(f"Tensorflow Version: \n{tf.__version__}")

Tensorflow Version: 
2.21.0


Dataset -> Batch -> Shuffle -> Map -> Prefetch -> Model

In [ ]:
# Cell 1 - Membuat Dataset
x = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])
dataset = tf.data.Dataset.from_tensor_slices(x) # 

print(f"x:\n{x} ")
print("Dataset")

for data in dataset: # pakai for agar bisa melihat dataset
    print(data.numpy())

x:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]] 
Dataset
[1.]
[2.]
[3.]
[4.]
[5.]


In [ ]:
# Cell 2 - Dataset Input dan Label
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0],
    [11.0]
])
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
print(f"Dataset")
for x, y in dataset:
    print(
        "x:",
        x.numpy(),
        "y:",
        y.numpy()
    )

Dataset
x: [1.] y: [3.]
x: [2.] y: [5.]
x: [3.] y: [7.]
x: [4.] y: [9.]
x: [5.] y: [11.]


In [ ]:
# Cell 3 - Batch
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.batch(2)
for x,y in dataset:
    print(f"\nBatch")

    print("x")
    print(x.numpy())
    print("y")
    print(y.numpy())


Batch
x
[[1.]
 [2.]]
y
[[3.]
 [5.]]

Batch
x
[[3.]
 [4.]]
y
[[7.]
 [9.]]

Batch
x
[[5.]]
y
[[11.]]


In [ ]:
# Cell 4 - Shuffle
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.shuffle( # agar datanya acak
    buffer_size=5 # karena total nya ada 5 data
)
print(f"Shuffle")
for x,y in dataset:
    print(
        x.numpy(),
        y.numpy()
    )

Shuffle
[2.] [5.]
[1.] [3.]
[5.] [11.]
[3.] [7.]
[4.] [9.]


In [ ]:
# Cell 5 - Map
dataset = tf.data.Dataset.from_tensor_slices(
    x_train
)
dataset = dataset.map(
    lambda x: x * 10
)
for data in dataset:
    print(data.numpy())

[10.]
[20.]
[30.]
[40.]
[50.]


In [ ]:
# Cell 6 - Shuffle + Batch
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.shuffle(5)
dataset = dataset.batch(2)

for x,y in dataset:
    print("\nBatch")
    print(x.numpy())
    print(y.numpy())


Batch
[[2.]
 [5.]]
[[ 5.]
 [11.]]

Batch
[[1.]
 [3.]]
[[3.]
 [7.]]

Batch
[[4.]]
[[9.]]


In [ ]:
# Cell 7 - Dataset Lengkap
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.shuffle(5)
dataset = dataset.batch(2)
dataset = dataset.prefetch(
    tf.data.AUTOTUNE
)
for x, y in dataset:
    print(f"\nData")
    print(x.numpy())
    print(y.numpy())


Data


[[1.]
 [5.]]
[[ 3.]
 [11.]]

Data
[[3.]
 [2.]]
[[7.]
 [5.]]

Data
[[4.]]
[[9.]]


In [ ]:
# Cell 8 - Training Menggunakan Dataset
dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.shuffle(5)
dataset = dataset.batch(2)

model = tf.keras.Sequential([ # Input -> dense(8) -> reLU -> Dense(1) -> Output
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse"
)
history = model.fit(
    dataset,
    epochs=100,
    verbose=0
)
print("Training selesai")
print(f"Loss akhir: \n{history.history['loss'][-1]}")

Training selesai
Loss akhir: 
4.1859450340271


In [ ]:
# Cell 9 - Prediksi
prediksi = model.predict(
    tf.constant([
        [10.0],
        [20.0],
        [30.0]
    ]),
    verbose=0
)
print("Prediksi")
for hasil in prediksi:
    print(hasil[0])

Prediksi
14.929917
28.873045
42.81617


In [ ]:
# Cell 10 - Studi Kasus Lengkap
x_train = tf.constant([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0],
    [6.0],
    [7.0],
    [8.0]
])

y_train = tf.constant([
    [3.0],
    [5.0],
    [7.0],
    [9.0],
    [11.0],
    [13.0],
    [15.0],
    [17.0]
])

dataset = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)
)
dataset = dataset.shuffle(8)
dataset = dataset.batch(4)
dataset = dataset.prefetch(
    tf.data.AUTOTUNE
)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation="relu"),
    tf.keras.layers.Dense(8),
    tf.keras.layers.Dense(1)
])
model.compile(
    optimizer="adam",
    loss="mse"
)
history = model.fit(
    x_train,
    y_train,
    epochs=200,
    verbose=0
)
print(f"Loss Akhir: {history.history['loss'][-1]}")

prediksi = model.predict(
    tf.constant([
        [10.0]
    ]),
    verbose=0
)

print(f"Prediksi x=10: \n{prediksi[0][0]}")

Loss Akhir: 5.58186149597168
Prediksi x=10: 
15.934526443481445
