In [49]:
import tensorflow as tf

print("Tensorflow Version : ", tf.__version__)


Tensorflow Version :  2.21.0


tf.constant = itu tidak bisa diubah
tf.Variable = itu bisa diubah tapi variable nya harus ditambahkan .numpy()
.assign_add = kelipatan nya
shape 1 dimensi = (element, )
shape 2 dimensi = (Baris, kolom)

In [ ]:
# CONSTANT TENSOR
a = tf.constant(10) # Membuat tensor berisi angka 10
b = tf.constant(20)

print(a)
print(b)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(20, shape=(), dtype=int32)


In [51]:
# OPERASI DASAR
tambah = a + b
kurang = a - b
kali = a * b
bagi = a / b

print("\nTambah: ", tambah.numpy())
print("Kurang: ", kurang.numpy())
print("Kali: ", kali.numpy())
print("Bagi: ", bagi.numpy())


Tambah:  30
Kurang:  -10
Kali:  200
Bagi:  0.5


In [52]:
# TENSOR VECTOR
vector = tf.constant([10, 20, 30, 40, 50])
print("\nVector")
print(vector)



Vector
tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [53]:
# TENSOR MATRIX
matrix = tf.constant([
    [1, 2, 3 ],
    [4, 5, 6]
])

print("\nMatrix")
print(matrix)


Matrix
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [54]:
# SHAPE
print("\nShape Vector:", vector.shape)
print("Shape Matrix: ", matrix.shape)


Shape Vector: (5,)
Shape Matrix:  (2, 3)


In [55]:
# VARIABLE
nilai  = tf.Variable(100)
print("\nNilai Awal: ", nilai.numpy())

nilai.assign(200)
print("Nilai Baru: ", nilai.numpy())



Nilai Awal:  100
Nilai Baru:  200


In [56]:
# LOOP
print("\nLoop Tensor")
for i in vector:
    print(i.numpy())



Loop Tensor
10
20
30
40
50


In [57]:
# IF ELSE
angka = tf.constant(80)
if angka.numpy() >= 75:
    print("\nLulus")

else:
    print("\nTidak Lulus")


Lulus


In [58]:
# WHILE
counter = tf.Variable(1)
print("\nWhile Loop")

while counter.numpy() <= 5:
    print(counter.numpy())
    counter.assign_add(1)


While Loop
1
2
3
4
5


In [59]:
# LATIHAN OPERASI
x = tf.constant(15)
y = tf.constant(5)

hasil1 = x + y
hasil2 = x - y
hasil3 = x * y
hasil4 = x / y

print("\nHasil Tambah: ", hasil1.numpy())
print("\nHasil kurang: ", hasil2.numpy())
print("\nHasil kali: ", hasil3.numpy())
print("\nHasil bagi: ", hasil4.numpy())


Hasil Tambah:  20

Hasil kurang:  10

Hasil kali:  75

Hasil bagi:  3.0
